apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: initial-install
    repoURL: https://github.com/FadiDahdouh/argocdtest
    targetRevision: HEAD
